import NavBar from "@/Components/NavBar";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import Footer from "@/Components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Travel</title>
      </head>
      <body className="h-full flex flex-col">
        <StoreProvider>
          <main className="flex-grow">{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
