import NavBar from "@/Components/NavBar";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import Footer from "@/Components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Travel</title>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        />

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet" />
      </head>
      <body className="h-full flex flex-col">
        <StoreProvider>
          <main className="flex-grow">{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}



